.\" Manpage for github-backup.sh.
.\" Contact moisesjbc@gmail.com to correct errors or typos.
.TH man 8 "31 May 2015" "0.1" "github-backup.sh man page"
.SH NAME
github-backup.sh \- Backup all the Github repositories of a given user.
.SH SYNOPSIS
github-backup.sh <Github user>
.SH DESCRIPTION
github-backup.sh is a backup script which clones all the remote repositories of a given Github user.
.SH OPTIONS
github-backup.sh does not take any options.
.SH BUGS
No known bugs.
.SH AUTHOR
Moisés J. Bonilla Caraballo (moisesjbc@gmail.com)
